apiVersion: apps/v1
kind: Deployment
metadata:
  name: temp
  namespace: test
  labels:
    app: temp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: temp
  template:
    metadata:
      labels:
        app: temp
    spec:
      containers:
      - name: temp
        image: daisukebtw/ipv4-page
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#            - matchExpressions:
#              - key: env
#                operator: In
#                values:
#                - dev
---
apiVersion: v1
kind: Service
metadata:
  name:  temp
  namespace: test
spec:
  selector:
    app:  temp
  # ---
  type:  ClusterIP
  ports:
  - name:  http
    port:  80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: temp9-ingress # Name of the ingress object
  namespace: test # Name of the namespace
spec:
  rules:
  - host: "temp9.citadel.home"  # Your hostname
    http:
      paths:
      # Path-based routing settings:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: temp  # The name of the service
            port:
              number: 80  # Service Portnumber
