apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-certificate
  namespace: test
spec:
  secretName: test
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - temp9.citadel.home
